spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prod
    username: prod_user
    password: password
    platform: mysgl
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false